name = "school-management-system"
main = "api/index.js"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]

assets = { directory = "./public" }

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.secrets]]
binding = "MONGODB_URI"
[[env.production.secrets]]
binding = "JWT_SECRET"
[[env.production.secrets]]
binding = "SESSION_SECRET"

[build]
command = "echo 'Skipping build'"